name: Feature request
description: Propose a new capability with scope and acceptance criteria.
title: "[feature] "
labels:
  - enhancement
body:
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Proposed solution and boundaries.
    validations:
      required: true
  - type: textarea
    id: non_goals
    attributes:
      label: Non-goals
      description: What this request should explicitly not do.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
