name: Engineering task (internal)
description: Internal execution tracker. External task issues are auto-closed by intake policy.
title: "[task] "
labels:
  - chore
body:
  - type: markdown
    attributes:
      value: |
        Internal-only template for maintainers.
        External contributors should use `Bug report` or `Feature request`.
  - type: input
    id: owner
    attributes:
      label: Owner
      description: GitHub handle of task owner.
      placeholder: "@ringxworld"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is in-scope for this task.
    validations:
      required: true
  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of scope
    validations:
      required: true
  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      placeholder: |
        - [ ] implement
        - [ ] validate
        - [ ] docs/tests
        - [ ] merge via PR
    validations:
      required: true
